# Generated by Django 5.1.1 on 2025-05-07 02:32

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('VIP', 'VIP'), ('Beta-tester', 'Beta-tester'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('total_sessions', models.BigIntegerField(default=0)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('daily_streak', models.BigIntegerField(default=0)),
                ('longest_daily_streak', models.BigIntegerField(default=0)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('points', models.BigIntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('completed_courses_lessons', models.JSONField(blank=True, default=dict)),
                ('completed_exercises', models.JSONField(blank=True, default=list)),
                ('content_history', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=8)),
                ('theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=15)),
                ('notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_classes', models.ManyToManyField(blank=True, to='courses.courselesson')),
                ('completed_courses', models.ManyToManyField(blank=True, related_name='completed_users', to='courses.course')),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='enrolled_users', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
