# Generated by Django 5.1.1 on 2025-05-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermetadata',
            old_name='completed_classes',
            new_name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='usermetadata',
            name='completed_courses_lessons',
        ),
    ]
