# Generated by Django 5.2.1 on 2025-09-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontentprogress',
            options={'ordering': ['last_update']},
        ),
        migrations.AddField(
            model_name='usercontentprogress',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
