# Generated by Django 5.1.1 on 2025-05-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_completed_classes_usermetadata_completed_lessons_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMetadata',
            new_name='UserAccount',
        ),
    ]
