# Generated by Django 5.1.1 on 2025-05-09 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_usermetadata_useraccount'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='completed_courses',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='completed_exercises',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='content_history',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='enrolled_courses',
        ),
        migrations.CreateModel(
            name='UserContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('in progress', 'in progress'), ('attempted', 'attempted'), ('later', 'later'), ('on hold', 'on hold'), ('dropped', 'dropped')], default='in progress', max_length=15)),
                ('object_id', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='accounts.useraccount')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
