# Generated by Django 5.1.1 on 2025-05-09 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccount_completed_courses_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usercontentprogress',
            index=models.Index(fields=['status'], name='accounts_us_status_c2ed66_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentprogress',
            index=models.Index(fields=['account'], name='accounts_us_account_eec8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontentprogress',
            index=models.Index(fields=['content_type'], name='accounts_us_content_97712a_idx'),
        ),
    ]
