# Generated by Django 5.1.1 on 2025-05-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
