services:  
  backend:
    build: ./backend
    container_name: "${PROJECT_NAME}_backend"
    command: "gunicorn backend.wsgi:application --bind 0.0.0.0:${BACKEND_PORT}"
    environment:
      VIRTUAL_HOST: ${BACKEND_DOMAIN}
      VIRTUAL_PORT: ${BACKEND_PORT} 
      LETSENCRYPT_HOST: ${BACKEND_DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    env_file:
      - .env.prod
    depends_on:
      - postgres
    restart: always
    networks:
      - nginx-proxy-net

  postgres:
    image: postgres:15
    container_name: "${PROJECT_NAME}_postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    restart: always  
    networks:
      - nginx-proxy-net

  frontend:
    build:
      context: ./frontend
    container_name: "${PROJECT_NAME}_frontend"
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 80 
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
      REACT_APP_API_URL: ${BACKEND_DOMAIN}

    depends_on:
      - backend
    restart: always
    networks:
      - nginx-proxy-net

volumes:
  postgres_data:

networks:
  nginx-proxy-net:
    external: true

