# Generated by Django 5.1.1 on 2024-12-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
