# Generated by Django 5.1.1 on 2025-01-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0003_course_courseclass_courseunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='nameId',
        ),
        migrations.RemoveField(
            model_name='courseunit',
            name='course_classes',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='units',
            field=models.ManyToManyField(related_name='classes', to='dataBase.courseunit'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
