# Generated by Django 5.1.1 on 2025-01-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0004_remove_course_nameid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='formulas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
