# Generated by Django 5.1.1 on 2025-01-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0005_alter_course_formulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
