# Generated by Django 5.1.1 on 2025-02-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0006_course_keywords_courseclass_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
