# Generated by Django 5.1.1 on 2025-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0007_classexerxise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExercise',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('problemText', models.CharField(max_length=511)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('problem', models.CharField(max_length=511)),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassExerxise',
        ),
    ]
