# Generated by Django 5.1.1 on 2025-01-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0008_classexercise_delete_classexerxise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexercise',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
