# Generated by Django 5.1.1 on 2025-01-25 05:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0009_alter_classexercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classexercise',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
