# Generated by Django 5.1.1 on 2025-01-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0011_alter_classexercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
