# Generated by Django 5.1.1 on 2025-01-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0012_alter_courseclass_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='content',
        ),
    ]
