# Generated by Django 5.1.1 on 2025-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0013_remove_courseclass_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='content',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
