# Generated by Django 5.1.1 on 2025-02-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0019_alter_courseclass_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
