# Generated by Django 5.1.1 on 2025-02-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0007_alter_course_keywords_alter_courseclass_keywords'),
        ('dataBase', '0020_alter_course_keywords_alter_courseclass_keywords'),
    ]

    operations = [
    ]
