# Generated by Django 5.1.1 on 2025-02-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0021_merge_20250215_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='content',
            field=models.TextField(),
        ),
    ]
