# Generated by Django 5.1.1 on 2025-03-06 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBase', '0023_alter_courseclass_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
