# Generated by Django 5.1.1 on 2025-05-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('math', 'Mathematics'), ('cs', 'Computer Science'), ('physics', 'Physics'), ('electronics', 'Electronics')], max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(max_length=255)),
                ('formulas', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('problemText', models.CharField(max_length=511)),
                ('image', models.URLField(blank=True, null=True)),
                ('problem', models.CharField(max_length=511)),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('test', 'Test')], max_length=50)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField()),
                ('units', models.ManyToManyField(related_name='classes', to='courses.courseunit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
