# Generated by Django 5.1.1 on 2025-05-09 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='class_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='completions',
        ),
        migrations.RemoveField(
            model_name='course',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='course',
            name='views',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='completions',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='views',
        ),
        migrations.CreateModel(
            name='ContentMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('completions', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=64)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
