# Generated by Django 5.1.1 on 2025-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_class_type_courselesson_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.JSONField(default=dict),
        ),
    ]
