# Generated by Django 5.1.1 on 2025-05-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courselesson_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselesson',
            old_name='units',
            new_name='unit',
        ),
    ]
