# Generated by Django 5.1.1 on 2025-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseunit',
            name='name',
            field=models.JSONField(default=dict),
        ),
    ]
