# Generated by Django 5.1.1 on 2025-05-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courselesson_level_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='units',
            field=models.ManyToManyField(related_name='lessons', to='courses.courseunit'),
        ),
    ]
